version: "3.7"

volumes:
  www:

services:

  # Services

  api: # Rest API
    image: placeos/rest-api:beta
    restart: always
    container_name: api
    hostname: api
    ports:
      - 127.0.0.1:8082:3000
    depends_on:
      - auth
      - elastic
      - etcd
      - redis
      - rethink
      - rubber-soul
    environment:
      - CORE_URL=http://core:3000
      - ENV=development
      - ES_HOST=elastic
      - ETCD_HOST=etcd
      - REDIS_URL=redis://redis:6379
      - RETHINKDB_DB=place_development
      - RETHINKDB_HOST=rethink
      - SG_ENV=development
      - TZ=$TZ
      # - PLACE_SECRET=$PLACE_SECRET
      # - JWT_SECRET=$SECRET_KEY_BASE

  auth: # Authentication Service
    image: placeos/auth
    restart: always
    container_name: auth
    hostname: auth
    ports:
      - 127.0.0.1:8081:8080
    # volumes:
    #   - ./placeos/services/auth/:/app/:ro
    depends_on:
      - rethink
    environment:
      - RETHINKDB_DB=place_development
      - RETHINKDB_HOST=rethink
      - COAUTH_NO_SSL=true
      - TZ=$TZ

  core: # Module coordinator
    image: placeos/core:beta
    restart: always
    container_name: core
    hostname: core
    ports:
      - 127.0.0.1:8083:3000
    depends_on:
      - etcd
      - redis
      - rethink
    volumes:
      - ./data/core-drivers:/app/bin/drivers
    environment:
      - ENV=development
      - ETCD_HOST=etcd
      - CORE_HOST=core
      - CORE_PORT=3000
      - REDIS_URL=redis://redis:6379
      - RETHINKDB_DB=place_development
      - RETHINKDB_HOST=rethink
      - SG_ENV=development
      - TZ=$TZ

  frontends: # Frontend deployment service
    image: placeos/frontends
    restart: always
    container_name: frontends
    hostname: frontends
    ports:
      - 127.0.0.1:8087:3000
    volumes:
      - type: volume
        source: www
        target: /app/www
    depends_on:
      - rethink
    environment:
      - ENV=development
      - PLACE_LOADER_WWW=www
      - RETHINKDB_DB=place_development
      - RETHINKDB_HOST=rethink
      - SG_ENV=development
      - TZ=$TZ

  triggers: # Conditional execution service
    image: placeos/triggers
    restart: always
    container_name: triggers
    hostname: triggers
    depends_on:
      - redis
      - rethink
    environment:
      - ENV=development
      - REDIS_URL=redis://redis:6379
      - RETHINKDB_DB=place_development
      - RETHINKDB_HOST=rethink
      - SG_ENV=development
      - TZ=$TZ

  # Support

  rubber-soul: # RethinkDB to Elasticsearch Service
    image: placeos/rubber-soul:v1.5.3
    restart: always
    container_name: rubber-soul
    hostname: rubber-soul
    ports:
      - 127.0.0.1:8084:3000
    depends_on:
      - elastic
      - rethink
    environment:
      - ES_HOST=elastic
      - RETHINKDB_DB=place_development
      - RETHINKDB_HOST=rethink
      - TZ=$TZ

  dispatch: # Engine driver server registration and data routing
    image: placeos/dispatch
    restart: always
    container_name: dispatch
    hostname: dispatch
    ports:
      - 127.0.0.1:8086:8080
    environment:
      - SERVER_SECRET=development

  # Resources

  elastic:
    image: blacktop/elasticsearch:7.6
    restart: always
    container_name: elastic
    hostname: elastic
    ports:
      - 127.0.0.1:8090:9200
    volumes:
      - ./data/elastic-data:/usr/share/elasticsearch/data:Z
    environment:
      - TZ=$TZ
      - bootstrap.memory_lock=true
      - cluster.routing.allocation.disk.threshold_enabled=false
      - discovery.type=single-node

  etcd:
    image: bitnami/etcd:3.3.13
    restart: always
    container_name: etcd
    hostname: etcd
    ports:
      - 127.0.0.1:8091:2379
      - 127.0.0.1:8092:2380
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
      - TZ=$TZ

  nginx:
    image: yobasystems/alpine-nginx
    restart: always
    container_name: nginx
    hostname: nginx
    ports:
      - 8080:80
      - 8443:443
    volumes:
      - ./config/nginx/nginx-nossl.conf:/etc/nginx/nginx.conf:Z
      - ./ssl/:/etc/nginx/ssl/:Z
      - type: volume
        source: www
        target: /etc/nginx/html/
        read_only: true
    environment:
      - TZ=$TZ

  redis:
    image: eqalpha/keydb
    restart: always
    container_name: redis
    hostname: redis
    ports:
      - 127.0.0.1:7379:6379
    volumes:
      - ./data/redis-data:/data:Z
      - ./config/redis.conf:/usr/local/etc/redis/redis.conf:Z
    environment:
      - TZ=$TZ

  rethink:
    image: rethinkdb:2.4
    restart: always
    container_name: rethink
    hostname: rethink
    ports:
      - 127.0.0.1:8093:8080
    volumes:
      - ./data/rethink-data:/data/rethinkdb_data/:Z
    environment:
      - TZ=$TZ

  # Development Specific

  play: # Crystal Play
    # Spawn a play process in desired directory `docker exec --workdir=${PROJECT_PATH} play crystal -p ${port}`
    # Presently, a single play session starts in `working_dir`.
    image: placeos/play:beta
    restart: always
    container_name: play
    hostname: play
    working_dir: /placeos/core
    entrypoint: crystal play -b 0.0.0.0 -p 4040
    ports:
      - 127.0.0.1:4040-4060:4040-4060 # Expose a range of ports for ssh
      - 127.0.0.1:4022:22 # Expose SSH
    environment:
      - CORE_URL=http://core:3000
      - ENV=development
      - ES_HOST=elastic
      - ETCD_HOST=etcd
      - REDIS_URL=redis://redis:6379
      - RETHINKDB_DB=place_development
      - RETHINKDB_HOST=rethink
      - SG_ENV=development
      - TZ=$TZ
