version: "3.9"

networks:
  placeos:
    name: placeos
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.231.0/24

volumes:
  elastic-data:
  influx-data:
  nginx-data:
  postgres-data:
  redis-data:
  rethink-data:
  www:

# YAML Anchors

x-deployment-env: &deployment-env
  ENV: ${ENV:-development}
  SG_ENV: ${SG_ENV:-development}
  TZ: $TZ

x-edge-env: &edge-env
  PLACE_EDGE_SECRET: ${PLACE_EDGE_SECRET:-}
  PLACE_URI: ${PLACE_URI:-http://api:3000}

x-jwt-public: &jwt-public .env.public_key

x-jwt-secret: &jwt-secret .env.secret_key

x-elastic-client-env: &elastic-client-env
  ES_HOST: ${ELASTIC_HOST:-elastic}
  ES_PORT: ${ELASTIC_PORT:-9200}

x-etcd-client-env: &etcd-client-env
  ETCD_HOST: ${ETCD_HOST:-etcd}
  ETCD_PORT: ${ETCD_PORT:-2379}

x-influxdb-api-key: &influxdb-api-key .env.influxdb

x-influxdb-client-env: &influxdb-client-env
  INFLUX_BUCKET: ${INFLUX_BUCKET:-place}
  INFLUX_HOST: ${INFLUX_HOST:-http://influxdb:8086}
  INFLUX_ORG: ${INFLUX_ORG:-PlaceOS}

x-place-loader-client-env: &place-loader-client-env
  PLACE_LOADER_URI: ${PLACE_LOADER_URI:-http://frontends:3000}

x-redis-client-env: &redis-client-env
  REDIS_URL: ${REDIS_URL:-redis://redis:6379}

x-rethinkdb-client-env: &rethinkdb-client-env
  RETHINKDB_HOST: ${RETHINKDB_HOST:-rethink}
  RETHINKDB_PORT: ${RETHINKDB_PORT:-28015}
  RETHINKDB_DB: ${RETHINKDB_DB:-place_development}

x-rubber-soul-client-env: &rubber-soul-client-env
  RUBBER_SOUL_URI: ${RUBBER_SOUL_URI:-http://rubber-soul:3000}

x-smtp-client-env: &smtp-client-env
  SMTP_SERVER: ${SMTP_SERVER:-}
  SMTP_PORT: ${SMTP_PORT:-587}
  SMTP_USER: ${SMTP_USER:-} # username if required, will not authenticate if blank
  SMTP_PASS: ${SMTP_PASS:-} # password if required
  SMTP_SECURE: ${SMTP_SECURE:-} # blank for unsecure, `SMTPS` for TLS, `STARTTLS` for negotiating TLS on unsecure connection

x-logging-env: &logging-env
  logging:
    driver: json-file
    options:
      max-size: 99m

services:
  # Services

  api: # Rest API
    image: placeos/rest-api:${PLACE_REST_API_TAG:-latest}
    restart: always
    container_name: api
    hostname: api
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - auth
      - elastic
      - etcd
      - redis
      - rethink
      - rubber-soul
    env_file:
      - *jwt-public
      - *jwt-secret
    environment:
      # Environment
      <<: *deployment-env
      # Service Hosts
      <<: *elastic-client-env
      <<: *etcd-client-env
      <<: *place-loader-client-env
      <<: *redis-client-env
      <<: *rethinkdb-client-env
      <<: *rubber-soul-client-env

  auth: # Authentication Service
    image: placeos/auth:${PLACE_AUTH_TAG:-latest}
    restart: always
    container_name: auth
    hostname: auth
    networks:
      placeos:
    <<: *logging-env
    healthcheck:
      # TODO: Remove after placeos-1.2109.0
      test: wget --no-verbose -q --spider http://0.0.0.0:8080/auth/authority?health=true
    depends_on:
      - redis
      - rethink
    env_file:
      - *jwt-secret
    environment:
      <<: *rethinkdb-client-env
      <<: *redis-client-env
      COAUTH_NO_SSL: "true"
      TZ: $TZ

  core: # Module coordinator
    image: placeos/core:${PLACE_CORE_TAG:-latest}
    restart: always
    container_name: core
    hostname: core
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - etcd
      - redis
      - rethink
    ulimits:
      nofile: 40000
      core:
        soft: 0
        hard: 0
    environment:
      # Service Hosts
      <<: *etcd-client-env
      <<: *redis-client-env
      <<: *rethinkdb-client-env
      # Environment
      <<: *deployment-env

  edge: # Module coordinator
    image: placeos/edge:${PLACE_EDGE_TAG:-latest}
    restart: "no"
    container_name: edge
    hostname: edge
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - core
    environment:
      <<: *edge-env
      <<: *deployment-env

  frontends: # Frontend deployment service
    image: placeos/frontends:${PLACE_FRONTENDS_TAG:-latest}
    restart: always
    container_name: frontends
    hostname: frontends
    networks:
      placeos:
    <<: *logging-env
    volumes:
      - type: volume
        source: www
        target: /app/www
    depends_on:
      - rethink
    environment:
      PLACE_LOADER_WWW: www
      <<: *rethinkdb-client-env
      # Environment
      <<: *deployment-env

  source:
    image: placeos/source:${PLACE_SOURCE_TAG:-latest}
    restart: always
    container_name: source
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - influxdb
      - redis
      - rethink
    env_file:
      - *influxdb-api-key
    environment:
      # Service Hosts
      <<: *influxdb-client-env
      <<: *redis-client-env
      <<: *rethinkdb-client-env
      # Environment
      <<: *deployment-env

  triggers: # Conditional execution service
    image: placeos/triggers:${PLACE_TRIGGERS_TAG:-latest}
    restart: always
    container_name: triggers
    hostname: triggers
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - core
      - etcd
      - redis
      - rethink
    environment:
      # Service Hosts
      <<: *etcd-client-env
      <<: *redis-client-env
      <<: *rethinkdb-client-env
      <<: *smtp-client-env
      # Environment
      <<: *deployment-env

  postgres: # Database used by Staff API
    image: postgres:${POSTGRES_VERSION:-13-alpine}
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      placeos:
    <<: *logging-env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      TZ: $TZ
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD

  staff: # Staff API
    image: placeos/staff-api:${PLACE_STAFF_API_TAG:-latest}
    container_name: staff
    hostname: staff
    restart: unless-stopped
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - api
      - postgres
    env_file:
      - .env.secret_key
      - .env.public_key
    environment:
      SG_ENV: production
      STAFF_TIME_ZONE: $TZ
      PG_DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/placeos"
      PLACE_URI: "https://nginx"
      SSL_VERIFY_NONE: "true"

  # Support

  init:
    image: placeos/init:${PLACE_INIT_TAG:-latest}
    container_name: init
    restart: on-failure
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - rethink
      - rubber-soul
    environment:
      # User/Application Configuration
      PLACE_DOMAIN: ${PLACE_DOMAIN:-localhost:8443}
      PLACE_APPLICATION: ${PLACE_APPLICATION:-backoffice}
      PLACE_AUTH_HOST: ${PLACE_AUTH_HOST:-auth:8080}
      PLACE_USERNAME: ${PLACE_USERNAME:-Place Support (localhost:8443)}
      PLACE_EMAIL: ${PLACE_EMAIL:-support@place.tech}
      PLACE_PASSWORD: ${PLACE_PASSWORD:-development}
      PLACE_TLS: "${PLACE_TLS:-true}"
      # Service Hosts
      <<: *rethinkdb-client-env
      <<: *elastic-client-env
      # Environment
      <<: *deployment-env

  rubber-soul: # RethinkDB to Elasticsearch Service
    image: placeos/rubber-soul:${PLACE_RUBBER_SOUL_TAG:-latest}
    restart: always
    container_name: rubber-soul
    hostname: rubber-soul
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - elastic
      - rethink
    environment:
      # Service Hosts
      <<: *rethinkdb-client-env
      <<: *elastic-client-env
      # Environment
      <<: *deployment-env

  dispatch: # Engine driver server registration and data routing
    image: placeos/dispatch:${PLACE_DISPATCH_TAG:-latest}
    restart: always
    container_name: dispatch
    hostname: dispatch
    networks:
      placeos:
    <<: *logging-env
    environment:
      SERVER_SECRET: ${PLACE_SERVER_SECRET:-development}

  # Resources

  elastic:
    image: amazon/opendistro-for-elasticsearch:${ELASTIC_OD_VERSION:-1.13.2}
    restart: always
    container_name: elastic
    hostname: elastic
    networks:
      placeos:
    <<: *logging-env
    healthcheck:
      test: wget -q --no-verbose --tries=1 --spider http://localhost:9200/_cat/health
    volumes:
      - type: volume
        source: elastic-data
        target: /usr/share/elasticsearch/data
    environment:
      bootstrap.memory_lock: "true"
      cluster.routing.allocation.disk.threshold_enabled: "false"
      discovery.type: single-node
      TZ: $TZ

  etcd:
    image: bitnami/etcd:${ETCD_VERSION:-3}
    restart: always
    container_name: etcd
    hostname: etcd
    networks:
      placeos:
    <<: *logging-env
    healthcheck:
      test: etcdctl endpoint health
    environment:
      ALLOW_NONE_AUTHENTICATION: "yes"
      TZ: $TZ

  influxdb:
    image: influxdb:${INFLUXDB_IMAGE_TAG:-2.0.8}-alpine
    restart: always
    container_name: influx
    hostname: influx
    networks:
      placeos:
    <<: *logging-env
    healthcheck:
      test: influx bucket list
    volumes:
      - type: volume
        source: influx-data
        target: /root/.influxdbv2
    command: "--reporting-disabled"

  nginx:
    image: placeos/nginx:${PLACE_NGINX_TAG:-nightly}
    restart: always
    container_name: nginx
    hostname: nginx
    ports:
      - 8080:80
      - 8443:443
    networks:
      placeos:
    <<: *logging-env
    depends_on:
      - api
      - auth
      - staff
    volumes:
      - type: volume
        source: www
        target: /etc/nginx/html/
        read_only: true
      - type: volume
        source: nginx-data
        target: /etc/nginx/
      - ${PWD}/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${PWD}/.htpasswd-kibana:/etc/nginx/.htpasswd-kibana
    env_file:
      - *jwt-public
      - *influxdb-api-key
    environment:
      TZ: $TZ
      PLACE_DOMAIN: ${PLACE_DOMAIN:-localhost:8443}

  redis:
    image: eqalpha/keydb
    restart: always
    container_name: redis
    hostname: redis
    networks:
      placeos:
    <<: *logging-env
    healthcheck:
      test: redis-cli ping
    volumes:
      - type: volume
        source: redis-data
        target: /data
    environment:
      TZ: $TZ

  rethink:
    image: rethinkdb:${RETHINKDB_VERSION:-2.4}
    restart: always
    container_name: rethink
    hostname: rethink
    networks:
      placeos:
    <<: *logging-env
    healthcheck:
      # Check if the DB's port is open
      test: "bash -c ': &>/dev/null </dev/tcp/127.0.0.1/28015'"
    volumes:
      - type: volume
        source: rethink-data
        target: /data/rethinkdb_data
    environment:
      TZ: $TZ

  # Aggregates logs and forwards them to Elasticsearch.
  logstash:
    image: blacktop/logstash:${ELASTIC_VERSION:-7.6}
    profiles:
      - kibana
    restart: always
    container_name: logstash
    hostname: logstash
    networks:
      placeos:
    << : *logging-env
    depends_on:
      - validate-logstash-config
    volumes:
      - ${PWD}/config/logstash/config:/config
      - ${PWD}/config/logstash/patterns:/opt/logstash/extra_patterns
    command: logstash -f /config

  # Run 'docker-compose run --rm validate-logstash-config' to quickly check the logstash config.
  validate-logstash-config:
    image: blacktop/logstash:${ELASTIC_VERSION:-7.6}
    profiles:
      - kibana
    restart: "no"
    container_name: validate-logstash
    volumes:
      - ${PWD}/config/logstash/config:/config
    command: logstash -t -f /config

  # Sends all container json-file logs to logstash
  logspout:
    image: vincit/logspout-gelf:3.2.6-alpine
    profiles:
      - kibana
    restart: unless-stopped
    hostname: $MONITOR_HOSTNAME
    container_name: logspout
    networks:
      placeos:
    << : *logging-env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: gelf://${LOGSTASH_HOST}:${LOGSTASH_PORT}

  kibana:
    image: amazon/opendistro-for-elasticsearch-kibana:${ELASTIC_OD_VERSION:-1.13.2}
    profiles:
      - kibana
    restart: always
    container_name: kibana
    hostname: kibana
    networks:
      placeos:
    << : *logging-env
    environment:
      - NODE_OPTIONS=--max-old-space-size=200 # fixes memory leak (https://github.com/elastic/kibana/issues/5170)
      - HTTPS_METHOD=nohttp
      - ELASTICSEARCH_HOSTS="http://${ELASTIC_HOST}:${ELASTIC_PORT}"
      - SERVER_BASEPATH="/${PLACE_METRICS_ROUTE}"
      - SERVER_REWRITEBASEPATH=true
      - SERVER_PUBLICBASEURL="https://${PLACE_DOMAIN}/${PLACE_METRICS_ROUTE}"

  # Takes care of piling up Elasticsearch indices/logs. Can do many other things as well.
  # Set up a cron job that runs "docker-compose run --rm curator --config /config.yml /action-file.yml" every once in a while.
  curator:
    image: bobrik/curator:5.7.6
    profiles:
      - kibana
    container_name: curator
    hostname: curator
    << : *logging-env
    volumes:
      - ${PWD}/config/curator/action-file.yml:/action-file.yml
      - ${PWD}/config/curator/config.yml:/config.yml

  # Gets metrics from host machine and send to elastic
  metricbeat:
    image: elastic/metricbeat:${ELASTIC_VERSION:-7.6}
    profiles:
      - metricbeat
    restart: unless-stopped
    hostname: $MONITOR_HOSTNAME
    container_name: metricbeat
    hostname: metricbeat
    user: root
    networks:
      placeos:
    << : *logging-env
    volumes:
      - /proc:/hostfs/proc:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /:/hostfs:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${PWD}/config/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    cap_add:
      - SYS_PTRACE
      - DAC_READ_SEARCH
    command: ["metricbeat", "-e", "--strict.perms=false", "-system.hostfs=/hostfs", "-E", "output.elasticsearch.hosts=[$ELASTIC_HOST:$ELASTIC_PORT]"]
