name: CI
on: push
jobs:
  test:
    name: "Test Install - version: ${{ matrix.version }}, stable: ${{ matrix.stable }}"
    runs-on: ubuntu-latest
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      matrix:
        stable: [true]
        version:
          - 1.2107.0
          - 1.2105.3
        include:
          - version: nightly
            stable: false
    steps:
      - uses: actions/checkout@v2
      - name: Run docker-compose test environment
        run: ./install
        env:
          PLACE_AUTH_TAG: ${{ matrix.version }}
          PLACE_CORE_TAG: ${{ matrix.version }}
          PLACE_DISPATCH_TAG: ${{ matrix.version }}
          PLACE_EDGE_TAG: ${{ matrix.version }}
          PLACE_FRONTENDS_TAG: ${{ matrix.version }}
          PLACE_INIT_TAG: ${{ matrix.version }}
          PLACE_REST_API_TAG: ${{ matrix.version }}
          PLACE_RUBBER_SOUL_TAG: ${{ matrix.version }}
          PLACE_SOURCE_TAG: ${{ matrix.version }}
          PLACE_TRIGGERS_TAG: ${{ matrix.version }}
          PLACE_STAFF_API_TAG: edge
          PLACE_NGINX_TAG: staff-api
