name: CI
on:
  push:
  schedule:
    - cron: "0 15 * * 1-5"

jobs:
  test-install:
    name: "Install ${{ !matrix.stable && '🚧 ' || '' }}- os: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        os:
          - ubuntu-18.04
          - ubuntu-20.04
        include:
          -
            os: windows-2022
            stable: false
          -
            os: macos-11
            stable: false
    steps:
      -
        # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
        name: Install Docker Machine on macos
        if: ${{ startsWith(matrix.os, 'macos') }}
        run: |
          mkdir -p ~/.docker/machine/cache
          curl -sSLo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v20.10.13/boot2docker.iso
          brew install docker docker-machine docker-compose bash
          docker-machine create --driver virtualbox default
          docker-machine env default
      -
        name: Install PlaceOS
        shell: bash
        run: |
          open () (
            echo "Navigated to ${1}"
          )

          PLACEOS_PARTNER_ENV_BRANCH="${GITHUB_REF#refs/heads/}" \
          curl \
          --proto '=https' \
          --tlsv1.2 \
          --show-error \
          --location \
          --silent \
          --fail \
          https://raw.githubusercontent.com/PlaceOS/partner-environment/${{ github.sha }}/scripts/install | bash
        env:
          PLACEOS_TAG: ${{ matrix.version }}
          PLACE_EMAIL: robot@place.tech
          PLACE_PASSWORD: development

  test-start:
    name: "Start ${{ !matrix.stable && '🚧 ' || '' }}- version: ${{ matrix.version != '' && matrix.version || 'empty'}}, os: ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        os:
          - ubuntu-18.04
          - ubuntu-latest
        version:
          - "" # Test an empty tag
          - placeos-1.2201.1
          - placeos-1.2202.2
          - placeos-1.2204.1
          - latest
          - preview
        include:
          - version: nightly
            stable: false
            os: ubuntu-18.04
          - version: nightly
            stable: false
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test initialization
        run: ./placeos start --verbose
        env:
          PLACEOS_TAG: ${{ matrix.version }}
          PLACE_EMAIL: robot@place.tech
          PLACE_PASSWORD: development
      - name: Test initialization, with unset PLACEOS_TAG
        if: ${{ matrix.version == '' }} # Testing an empty tag
        run: |
          docker-compose down --volumes &> /dev/null
          rm .env.*
          ./placeos start --verbose
        env:
          PLACE_EMAIL: robot@place.tech
          PLACE_PASSWORD: development
          ETCD_VERSION: 3.5.1
      - name: Upload logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.os }}-${{ matrix.version }}-${{ github.sha }}
          path: .logs/*.log
      - name: List service statuses
        run: docker-compose ps
      - name: Check API is reachable
        continue-on-error: true
        run: curl --retry 10 --insecure -fsSL https://localhost:8443/api/engine/v2
      - name: Test raw `docker-compose`
        run: docker-compose down
