name: CI
on: push
jobs:
  test:
    name: "Test Install - os: ${{ matrix.os }}, version: ${{ matrix.version }}, stable: ${{ matrix.stable }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        os:
          - ubuntu-18.04
          - ubuntu-latest
        version:
          - placeos-1.2107.1
          - placeos-1.2105.3
        include:
          - version: nightly
            stable: false
            os: ubuntu-18.04
          - version: nightly
            stable: false
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spin up environment
        run: ./placeos start
        env:
          PLACEOS_TAG: ${{ matrix.version }}
      - name: Healthcheck
        run: curl --insecure https://localhost:8443/api/engine/v2
      - name: List service statuses
        run: docker-compose ps
