name: CI
on: push
jobs:
  test:
    name: "Test Install - os: ${{ matrix.os }}, version: ${{ matrix.version }}, stable: ${{ matrix.stable }}"
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ !matrix.stable }}
    strategy:
      fail-fast: false
      matrix:
        stable: [true]
        os:
          - ubuntu-18.04
          - ubuntu-latest
        version:
          - placeos-1.2105.3
          - placeos-1.2107.4
          - placeos-1.2108.1
        include:
          - version: nightly
            stable: false
            os: ubuntu-18.04
          - version: nightly
            stable: false
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spin up environment
        run: ./placeos start --verbose
        env:
          PLACEOS_TAG: ${{ matrix.version }}
          PLACE_EMAIL: robot@place.tech
          PLACE_PASSWORD: development
      - name: Upload logs
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: logs-${{ matrix.os }}-${{ matrix.version }}-${{ github.sha }}
          path: .logs/*.log
      - name: List service statuses
        run: docker-compose ps
      - name: Check API is reachable
        run: curl --retry 10 --insecure -fsSL https://localhost:8443/api/engine/v2
