name: Render Compose Graph
on:
  push:
    paths:
      - docker-compose.yml
      - .github/workflows/render-compose.yml
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate graph
        run: |
          chmod 777 images
          docker run --network none --rm -v $(pwd):/input:rw pmsipilot/docker-compose-viz \
             render --force \
             -m image \
             --horizontal \
             --no-volumes --no-networks \
             -o ./images/service-graph.png \
             docker-compose.yml
      - name: Commit and push
        shell: bash
        run: |
          git config user.email "robots@place.technology"
          git config user.name "PlaceOS Robot"
          git add images/service-graph.png
          git commit --message="docs: update service graph for changes in ${{ github.head_ref }}"
          git push
