name: Render Compose Graph
on:
  push:
    branches:
      - "master"
    paths:
      - "docker-compose.yml"
      - ".github/workflows/render-compose.yml"
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Generate graph
        run: |
          chmod 777 images
          docker run --network none --rm -v $(pwd):/input:rw pmsipilot/docker-compose-viz \
             render --force \
             -m image \
             --horizontal \
             --no-volumes --no-networks \
             -o ./images/service-graph.png \
             docker-compose.yml
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          file_pattern: "./images/service-graph.png"
          commit_message: "docs: update service graph for changes in ${{ github.head_ref }}"
          commit_user_email: "robots@place.technology"
          commit_user_name: "PlaceOS Robot"
          disable_globbing: true
