on:
  pull_request_target:
    types:
      - closed

jobs:
  tag:
    name: Tag new release
    if: github.event.pull_request.merged == 'true' && startsWith(github.event.pull_request.title, 'release/')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure git user
        run: |
          git config user.email "robots@place.technology"
          git config user.name "PlaceOS Robot"

      - name: Tag the latest release
        shell: bash
        run: |
          source .env
          git tag "${PLACEOS_TAG}"
          git push --tags
