name: Update to latest release

on:
  repository_dispatch:
    types: [update]

env:
  VERSION_REGEX: '^[0-9]+\.[0-9]{4}\.[0-9]+$'

jobs:
  latest:
    name: Get latest PlaceOS version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        repository: PlaceOS/PlaceOS
    - name: Get latest version from PlaceOS/PlaceOS
      id: version
      run: |
        latest=$(git tag --list | grep --extended-regexp '${{ env.VERSION_REGEX }}' | sort | tail -1)
        echo ::set-output name=version::$latest

  update:
    name: Update
    needs: latest
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Update files
      id: update
      shell: bash
      run: |
        set -euo pipefail
        set -x #echo on

        branch=release/${{ needs.latest.outputs.version }}
        echo ::set-output name=branch::$branch

        # Update `.env`
        sed --in-place=.bak -E 's/^PLACEOS_TAG=.*/PLACEOS_TAG=${PLACEOS_TAG:-placeos-${{ needs.latest.outputs.version }}}/g' \
            .env

        # Update CI matrix
        sed --in-place=.bak -E 's/^([ ]{10}- )(latest)/\1placeos-${{ needs.latest.outputs.version }}\n\1\2/g' \
            .github/workflows/ci.yml

    - name: Commit and Push
      uses: github-actions-x/commit@v2.9
      with:
        message: 'build: update to ${{ needs.latest.outputs.version }}'
        files: .env .github/workflows/ci.yml
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: ${{ steps.update.outputs.branch }}
        name: PlaceOS Robot
        email: robots@placeos.com

    - name: Create PR
      shell: bash
      run: |
        # Login with GitHub CLI
        echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

        # Create PR
        gh pr create \
            --fill \
            --head '${{ steps.update.outputs.branch }}' \
            --label 'type: maintenance' \
            --base master \
            --body 'See the details for `placeos-${{ needs.latest.outputs.version }}`[here](https://github.com/PlaceOS/PlaceOS/releases/tag/${{ needs.latest.outputs.version }}).'
